/**
 * Few-shot design examples.
 *
 * Each example shows the model the exact tool-call sequence it should produce
 * for a given brief. These are injected as fake assistant/tool turns before
 * the real user prompt so the model learns the expected call order, naming
 * conventions, and layout patterns.
 */

export interface ExampleToolCall {
  tool: string;
  args: Record<string, unknown>;
}

export interface DesignExample {
  brief: string;
  toolCalls: ExampleToolCall[];
}

export const examples: DesignExample[] = [
  // ── Example 1: Q&A hook slide (warm gradient, pill label, CTA chip) ──────
  {
    brief:
      "Q&A carousel: How to start a business from scratch (if you've never done it before). Friendly, approachable.",
    toolCalls: [
      {
        tool: "startSlide",
        args: { slideNumber: 1, role: "hook" },
      },
      {
        tool: "setPalette",
        args: { background: "#FFF8F0", text: "#3D2C1E", accent: "#E8663D", secondary: "#F2A987", neutral: "#B8A492" },
      },
      {
        tool: "setGradientBackground",
        args: { from: "#FFF8F0", to: "#FFE8D6", angle: 160 },
      },
      {
        tool: "addStackElement",
        args: {
          kind: "stack",
          x: 80,
          y: 253,
          width: 920,
          rotation: 0,
          direction: "column",
          alignItems: "center",
          justifyContent: "start",
          gap: 20,
          paddingX: 0,
          paddingY: 0,
          children: [
            {
              kind: "text",
              width: 101,
              content: "Q&A",
              font: "body",
              fontSize: 26,
              fontWeight: 700,
              color: "background",
              align: "center",
              italic: false,
              uppercase: true,
              lineHeight: 1.1,
              letterSpacing: 2,
              background: "accent",
              paddingX: 22,
              paddingY: 10,
              borderRadius: 32,
            },
            {
              kind: "text",
              width: 920,
              content: "How to start a business from scratch",
              segments: [
                { text: "How to start a business " },
                { text: "from scratch", color: "accent" },
              ],
              font: "heading",
              fontSize: 92,
              fontWeight: 500,
              color: "text",
              align: "center",
              italic: false,
              uppercase: false,
              lineHeight: 1.1,
              letterSpacing: 0,
              paddingX: 0,
              paddingY: 0,
              borderRadius: 0,
            },
            {
              kind: "text",
              width: 900,
              content: "(if you've never done it before)",
              font: "body",
              fontSize: 36,
              fontWeight: 400,
              color: "text",
              align: "center",
              italic: true,
              uppercase: false,
              lineHeight: 1.2,
              letterSpacing: 0,
              paddingX: 0,
              paddingY: 0,
              borderRadius: 0,
            },
            {
              kind: "text",
              width: 260,
              content: "Start",
              font: "body",
              fontSize: 40,
              fontWeight: 500,
              color: "text",
              align: "center",
              italic: false,
              uppercase: false,
              lineHeight: 1.1,
              letterSpacing: 0,
              background: "accent",
              paddingX: 56,
              paddingY: 16,
              borderRadius: 999,
            },
          ],
        },
      },
      {
        tool: "startSlide",
        args: { slideNumber: 2, role: "tip 1" },
      },
      {
        tool: "setPalette",
        args: { background: "#FFF8F0", text: "#3D2C1E", accent: "#E8663D", secondary: "#F2A987", neutral: "#B8A492" },
      },
      {
        tool: "setSolidBackground",
        args: { color: "background" },
      },
      {
        tool: "addStackElement",
        args: {
          kind: "stack",
          x: 80,
          y: 320,
          width: 920,
          rotation: 0,
          direction: "column",
          alignItems: "start",
          justifyContent: "start",
          gap: 24,
          paddingX: 0,
          paddingY: 0,
          children: [
            {
              kind: "text",
              width: 180,
              content: "TIP #1",
              font: "body",
              fontSize: 26,
              fontWeight: 500,
              color: "background",
              align: "center",
              italic: false,
              uppercase: true,
              lineHeight: 1.1,
              letterSpacing: 2,
              background: "accent",
              paddingX: 22,
              paddingY: 10,
              borderRadius: 32,
            },
            {
              kind: "text",
              width: 920,
              content: "Validate your idea before you build",
              font: "heading",
              fontSize: 72,
              fontWeight: 500,
              color: "text",
              align: "left",
              italic: false,
              uppercase: false,
              lineHeight: 1.1,
              letterSpacing: 0,
              paddingX: 0,
              paddingY: 0,
              borderRadius: 0,
            },
            {
              kind: "text",
              width: 880,
              content: "Talk to 10 people who have the problem before writing a single line of code.",
              font: "body",
              fontSize: 40,
              fontWeight: 400,
              color: "text",
              align: "left",
              italic: false,
              uppercase: false,
              lineHeight: 1.3,
              letterSpacing: 0,
              paddingX: 0,
              paddingY: 0,
              borderRadius: 0,
            },
          ],
        },
      },
      {
        tool: "startSlide",
        args: { slideNumber: 3, role: "CTA" },
      },
      {
        tool: "setPalette",
        args: { background: "#FFF8F0", text: "#3D2C1E", accent: "#E8663D", secondary: "#F2A987", neutral: "#B8A492" },
      },
      {
        tool: "setGradientBackground",
        args: { from: "#FFF8F0", to: "#FFE8D6", angle: 160 },
      },
      {
        tool: "addStackElement",
        args: {
          kind: "stack",
          x: 80,
          y: 400,
          width: 920,
          rotation: 0,
          direction: "column",
          alignItems: "center",
          justifyContent: "start",
          gap: 48,
          paddingX: 0,
          paddingY: 0,
          children: [
            {
              kind: "text",
              width: 920,
              content: "Ready to take the first step?",
              font: "heading",
              fontSize: 80,
              fontWeight: 500,
              color: "text",
              align: "center",
              italic: false,
              uppercase: false,
              lineHeight: 1.1,
              letterSpacing: 0,
              paddingX: 0,
              paddingY: 0,
              borderRadius: 0,
            },
            {
              kind: "text",
              width: 280,
              content: "Swipe →",
              font: "body",
              fontSize: 40,
              fontWeight: 500,
              color: "text",
              align: "center",
              italic: false,
              uppercase: false,
              lineHeight: 1.1,
              letterSpacing: 0,
              background: "accent",
              paddingX: 56,
              paddingY: 16,
              borderRadius: 999,
            },
          ],
        },
      },
    ],
  },
];
